// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// lda_vem
List lda_vem(unsigned int num_topics, unsigned int vocab_size, List docs_tf, double alpha_h, double eta_h, unsigned int vi_max_iter, unsigned int em_max_iter, double vi_conv_thresh, double em_conv_thresh, bool estimate_alpha, bool estimate_eta, int verbose);
RcppExport SEXP ldavem_lda_vem(SEXP num_topicsSEXP, SEXP vocab_sizeSEXP, SEXP docs_tfSEXP, SEXP alpha_hSEXP, SEXP eta_hSEXP, SEXP vi_max_iterSEXP, SEXP em_max_iterSEXP, SEXP vi_conv_threshSEXP, SEXP em_conv_threshSEXP, SEXP estimate_alphaSEXP, SEXP estimate_etaSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< unsigned int >::type num_topics(num_topicsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type vocab_size(vocab_sizeSEXP);
    Rcpp::traits::input_parameter< List >::type docs_tf(docs_tfSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_h(alpha_hSEXP);
    Rcpp::traits::input_parameter< double >::type eta_h(eta_hSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type vi_max_iter(vi_max_iterSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type em_max_iter(em_max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type vi_conv_thresh(vi_conv_threshSEXP);
    Rcpp::traits::input_parameter< double >::type em_conv_thresh(em_conv_threshSEXP);
    Rcpp::traits::input_parameter< bool >::type estimate_alpha(estimate_alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type estimate_eta(estimate_etaSEXP);
    Rcpp::traits::input_parameter< int >::type verbose(verboseSEXP);
    __result = Rcpp::wrap(lda_vem(num_topics, vocab_size, docs_tf, alpha_h, eta_h, vi_max_iter, em_max_iter, vi_conv_thresh, em_conv_thresh, estimate_alpha, estimate_eta, verbose));
    return __result;
END_RCPP
}
// sample_multinomial
unsigned int sample_multinomial(arma::vec theta);
RcppExport SEXP ldavem_sample_multinomial(SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    __result = Rcpp::wrap(sample_multinomial(theta));
    return __result;
END_RCPP
}
// sample_dirichlet
arma::vec sample_dirichlet(unsigned int num_elements, arma::vec alpha);
RcppExport SEXP ldavem_sample_dirichlet(SEXP num_elementsSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< unsigned int >::type num_elements(num_elementsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha(alphaSEXP);
    __result = Rcpp::wrap(sample_dirichlet(num_elements, alpha));
    return __result;
END_RCPP
}
